WON-Corp/WonPick

- serchPage.html
검색페이지 검색기록 및 탐색페이지 슬라이드 효과 추가하여 커밋
> 검색페이지 작업후 커밋

- serchPage.html
> 검색페이지 재수정후 업로드

- wonpick/src/main/webapp/WEB-INF/views/wonPick.jsp
> 필요없는 주석 및 테스트용 로그 삭제

- .gitignore
**/.springBeans
**/target
두개의 파일과 폴더는 개인 PC 에서 생성되는 파일이기 때문에 꼭 같이 커밋을 안해도 상관없어서 제외 추가.
> .gitignore 내용 추가

- wonpick/src/main/webapp/WEB-INF/views/wonPick.jsp
> 이전에 스토리 7개 띄우는 걸로 바꿧는데 적용 안되어 적용

- MEMBER_data.sql
- wonpick/src/main/webapp/WEB-INF/views/wonPick.jsp
메인페이지 문제신고 모달 신고 제목 input태그 추가,
sql 문 수정 (테스트용 user 계정 추가)
> 문제 신고 모달 수정

- wonpick/src/main/webapp/WEB-INF/views/common/menuBar.jsp
> 네가 사용할  패패패패키지명

- wonpick/src/main/webapp/WEB-INF/views/common/menuBar.jsp
동영상 미리보기 스크립트 부분에서 파일이 이미지인지 동영상인지 판단 후 동영상 일시 동영상 미리볼 수 있게 하고 이미지면 이미지가 미리볼 수 있게 수정
이미지 변경 클릭시 기존 파일이 삭제됨.
> 동영상 미리보기 이미지 변경 후 취소 클릭시 기존 파일 삭제

- wonpick/src/main/webapp/WEB-INF/views/common/menuBar.jsp
> 로그아웃 경로 수정

- wonpick/src/main/java/com/won/wonpick/postLike/controller/PostLikeController.java
- wonpick/src/main/java/com/won/wonpick/postLike/model/dao/PostLikeDao.java
- wonpick/src/main/java/com/won/wonpick/postLike/model/vo/PostLike.java
- wonpick/src/main/java/com/won/wonpick/postLike/service/PostLikeService.java
- wonpick/src/main/java/com/won/wonpick/postLike/service/PostLikeServiceImpl.java
- wonpick/src/main/resources/mappers/postLike-mapper.xml
- wonpick/src/main/resources/mybatis-config.xml
- wonpick/src/main/webapp/WEB-INF/views/wonPick.jsp
- wonpick/target/classes/mybatis-config.xml
> 댓글 onerror 수정, 좋아요 기능 일부 구현

- wonpick/src/main/resources/mappers/post-mapper.xml
- wonpick/target/classes/mappers/post-mapper.xml
> sql에 따른 매퍼 변경

- wonpick/src/main/java/com/won/wonpick/savelist/controller/SaveListController.java
- wonpick/src/main/java/com/won/wonpick/savelist/model/dao/SaveListDao.java
- wonpick/src/main/java/com/won/wonpick/savelist/service/SaveListService.java
- wonpick/src/main/java/com/won/wonpick/savelist/service/SaveListServiceImpl.java
- wonpick/src/main/resources/mappers/saveList-mapper.xml
- wonpick/src/main/webapp/WEB-INF/views/wonPick.jsp
> 저장게시물 중복 저장 막았습니다.

- wonpick/src/main/java/com/won/wonpick/postLike/controller/PostLikeController.java
> 테스트용 sysout 삭제

- wonpick/src/main/webapp/WEB-INF/views/wonPick.jsp
> 게시물 모달 버튼 모양 숨김

- wonpick/src/main/webapp/WEB-INF/views/option/myprofile.jsp
> 호버시 텍스트 데코레이션 삭제

- wonpick/src/main/java/com/won/wonpick/postLike/controller/PostLikeController.java
- wonpick/src/main/webapp/WEB-INF/views/wonPick.jsp
> 좋아요 눌렀을 때 아이콘 바뀌고 로그인 했을 때 좋아요 누른 게시물 좋아요 누른 아이콘으로 표시

- wonpick/src/main/java/com/won/wonpick/admin/controller/AdminController.java
- wonpick/src/main/java/com/won/wonpick/admin/model/dao/AdminDao.java
- wonpick/src/main/java/com/won/wonpick/admin/service/AdminService.java
- wonpick/src/main/java/com/won/wonpick/admin/service/AdminServiceImpl.java
- wonpick/src/main/resources/mappers/admin-mapper.xml
- wonpick/src/main/webapp/WEB-INF/views/admin/manageReports.jsp
> 그 뭐야 그 문제신고 페이지 완료해버림

- wonpick/src/main/resources/mappers/admin-mapper.xml
- wonpick/src/main/webapp/WEB-INF/views/admin/adminMain.jsp
- wonpick/src/main/webapp/WEB-INF/views/admin/managePosts.jsp
- wonpick/src/main/webapp/WEB-INF/views/admin/manageReports.jsp
> Main에 admin-mapper 날아간 거 복구

- wonpick/src/main/java/com/won/wonpick/admin/controller/AdminController.java
> 리다이렉팅 주소 오류 수정

- wonpick/src/main/java/com/won/wonpick/postComment/controller/PostCommentController.java
- wonpick/src/main/webapp/WEB-INF/views/board/videoList.jsp
- wonpick/src/main/webapp/WEB-INF/views/option/profileInfo.jsp
- wonpick/src/main/webapp/WEB-INF/views/option/profileInfoPostList.jsp
- wonpick/src/main/webapp/WEB-INF/views/option/savedPostList.jsp
- wonpick/src/main/webapp/WEB-INF/views/search/searchList.jsp
- wonpick/src/main/webapp/WEB-INF/views/wonPick.jsp
> 댓글 모든부분 반응형으로 구현

- wonpick/src/main/resources/mappers/member-mapper.xml
- wonpick/src/main/webapp/WEB-INF/views/common/menuBar.jsp
- wonpick/src/main/webapp/WEB-INF/views/common/storyBar.jsp
- wonpick/src/main/webapp/WEB-INF/views/message/message.jsp
- wonpick/target/classes/mappers/member-mapper.xml
> 스토리바 클릭시 페이징 처리

- wonpick/src/main/java/com/won/wonpick/postLike/controller/PostLikeController.java
- wonpick/src/main/java/com/won/wonpick/savelist/controller/SaveListController.java
> 저장목록 오류 수정

- wonpick/src/main/java/com/won/wonpick/postLike/controller/PostLikeController.java
- wonpick/src/main/webapp/WEB-INF/views/wonPick.jsp
> 모달창에 좋아요 게시물 저장 마저 구현

- wonpick/src/main/webapp/WEB-INF/views/board/videoList.jsp
- wonpick/src/main/webapp/WEB-INF/views/option/profileInfoPostList.jsp
- wonpick/src/main/webapp/WEB-INF/views/option/savedPostList.jsp
- wonpick/src/main/webapp/WEB-INF/views/wonPick.jsp
> 영상게시물, 저장목록, 내프로필 게시물 부분 모달창에 게시물 좋아요, 저장  구현

- wonpick/src/main/java/com/won/wonpick/postLike/controller/PostLikeController.java
- wonpick/src/main/webapp/WEB-INF/views/board/videoList.jsp
- wonpick/src/main/webapp/WEB-INF/views/option/profileInfoPostList.jsp
- wonpick/src/main/webapp/WEB-INF/views/option/savedPostList.jsp
- wonpick/src/main/webapp/WEB-INF/views/search/searchList.jsp
- wonpick/src/main/webapp/WEB-INF/views/wonPick.jsp
> 페이지 콘솔창, 개발툴 콘솔창, 찍히던거 제거
